swagger: "2.0"
info:
  description: "Describes the HTTP Interface to a Phase One Digital Back"
  version: "1.0.0"
  title: "Phase One Capture Server API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "PhaseOne.local"
basePath: "/"
schemes:
- "http"
parameters:
  host:
    name: "Host"
    type: "string"
    in: "header"
    description: "The hostname of the digital back"
    default: "PhaseOne.local."
    required: true
  sessionId:
    name: "sessionID"
    type: "integer"
    in: "query"
    description: "The integer id of the session created from /connectToService"
    required: true
  imageId:
    name: "id"
    type: "string"
    in: "query"
    description: "The image ID, found in the variants array of getServerChanges"
    required: true
  timestamp:
    name: "timestamp"
    type: "integer"
    in: "query"
    description: "Unix timestamp in seconds"
    default: 632680049
    required: true
  
paths:
  /connectToService: 
    get: 
      summary: "Creates a new session ID to control the back"
      produces:
        - text/html
      responses: 
        '200':
          description: Integer ID of the session
      parameters: 
        - $ref: '#/parameters/host'
        - $ref: '#/parameters/timestamp'
        - 
          name: "Authorization"
          type: "string"
          in: "header"
          description: "Used only with this endpoint. base64(Guest:)"
          default: "Basic R3Vlc3Q6"
          required: true
        - 
          name: "protocolVersion"
          type: "string"
          in: "query"
          description: "Was 3.1 with an IQ3 Achro"
          default: 3.1
          required: true
        - 
          name: "deviceName"
          type: "string"
          in: "query"
          description: "Your device's hostname"
          required: true
        - 
          name: "deviceIdentifier"
          type: "string"
          in: "query"
          description: "Your devices's UUID"
          required: true
        - 
          name: "dataFormat"
          type: "string"
          in: "query"
          description: "The data format to use, json is default"
          default: json
          required: true
        - 
          name: "captureControlsOnly"
          type: "integer"
          in: "query"
          description: "Allow listing and getting images, or just the capture interface"
          required: true
  /getServerChanges: 
    get: 
      summary: "Returns a big json of data about the digital back"
      parameters: 
        - $ref: '#/parameters/host'
        - $ref: '#/parameters/sessionId'
      responses: 
        200: 
          description: "Information about the digital Back"
          schema: 
            type: "object"
            properties: 
              variants: 
                type: "array"
                items: 
                  type: "string"
                  description: ""
              objects: 
                type: "array"
                items: 
                  type: "object"
                  properties: 
                    kObjectKey_ObjectType: 
                      type: "string"
                      description: ""
                    kObjectKey_ObjectID: 
                      type: "string"
                      description: ""
                    kObjectKey_ChangeType: 
                      type: "string"
                      description: ""
                    kObjectKey_ObjectName: 
                      type: "string"
                      description: ""
                    kObjectKey_Properties: 
                      type: "array"
                      items: 
                        type: "object"
                        properties: 
                          kObjectProperty_PropertyID: 
                            type: "string"
                            description: ""
                          kObjectProperty_PropertyName: 
                            type: "string"
                            description: ""
                          kObjectProperty_ValueType: 
                            type: "string"
                            description: ""
                          kObjectProperty_Permissions: 
                            type: "string"
                            description: ""
                          kObjectProperty_Values: 
                            type: "string"
                            description: ""
                          kObjectProperty_CurrentValue: 
                            type: "string"
                            description: ""
              revision: 
                type: "string"
                description: ""
  /getImageMetadata: 
    get: 
      summary: "Gets the EXIF metadata for a specific image id."
      parameters: 
        - $ref: '#/parameters/host'
        - $ref: '#/parameters/imageId'
        - $ref: '#/parameters/sessionId'
        - $ref: '#/parameters/timestamp'
      responses: 
        200: 
          description: ""
          schema: 
            type: "object"
            properties: 
              kVariantKey_VariantID: 
                type: "string"
                description: ""
              kVariantKey_ImageID: 
                type: "string"
                description: ""
              kVariantKey_VariantName: 
                type: "string"
                description: ""
              kVariantKey_VariantNo: 
                type: "number"
                description: ""
              kVariantKey_ChangeType: 
                type: "string"
                description: ""
              kVariantKey_Properties: 
                type: "object"
                properties: 
                  kVariantProperty_Editable: 
                    type: "boolean"
                    description: ""
                  kVariantProperty_ISO: 
                    type: "string"
                    description: ""
                  kVariantProperty_ShutterSpeed: 
                    type: "string"
                    description: ""
                  kVariantProperty_Aperture: 
                    type: "string"
                    description: ""
                  kVariantProperty_FocalLength: 
                    type: "string"
                    description: ""
                  kVariantProperty_ImageCompression: 
                    type: "string"
                    description: ""
                  kVariantProperty_WhiteBalanceMode: 
                    type: "string"
                    description: ""
                  kVariantProperty_Width: 
                    type: "number"
                    description: ""
                  kVariantProperty_Height: 
                    type: "number"
                    description: ""
                  kVariantProperty_Rating: 
                    type: "number"
                    description: ""
                  kVariantProperty_ExposureDate: 
                    type: "number"
                    description: ""
  /getImage: 
    get: 
      summary: "Get an (part?) of an image from the digital back."
      produces: 
       - binary
      responses:
        200:
          description: OK
      parameters: 
        - $ref: '#/parameters/host'
        - $ref: '#/parameters/imageId'
        - $ref: '#/parameters/sessionId'
        - 
          name: "height"
          type: "integer"
          in: "query"
          description: "The height of the image to return"
          required: true
        - 
          name: "bottom"
          type: "integer"
          in: "query"
          description: "???"
          default: 0
          required: true

        - 
          name: "width"
          type: "integer"
          in: "query"
          description: "The width of the image to return"
          required: true
        - 
          name: "left"
          type: "integer"
          in: "query"
          default: 0
          description: "???"
          required: true
        - 
          name: "top"
          type: "integer"
          in: "query"
          description: "???"
          default: 0
          required: true
        - 
          name: "right"
          type: "string"
          in: "query"
          default: 0
          description: "???"
          required: true
        - 
          name: "overlay"
          type: "integer"
          in: "query"
          default: 0
          description: ""
          required: true
  /setProperty: 
    get: 
      summary: "Sets any rw property on the digital back"
      responses:
        200:
          description: "Returns 200, but no content ¯\_(ツ)_/¯"
      description: "The property IDs and allowed values are found in /getServerChanges."
      parameters: 
        - $ref: '#/parameters/host'
        - $ref: '#/parameters/imageId'
        - $ref: '#/parameters/timestamp'
        - 
          name: "propertyValue"
          type: "string"
          in: "query"
          description: "The value to set for this property"
          required: true
        - 
          name: "objectID"
          type: "string"
          in: "query"
          description: "The id of the object where this property is"
          required: true
        - 
          name: "propertyID"
          type: "string"
          in: "query"
          description: "The id of the property"
          required: true
        - 
          name: "objectType"
          type: "string"
          in: "query"
          description: "The type of the object where this property us"
          required: true
  /capture: 
    get: 
      summary: "Captures an image with the digital back!"
      parameters: 
        - $ref: '#/parameters/host'
        - $ref: '#/parameters/sessionId'
        - $ref: '#/parameters/timestamp'
        - 
          name: "cameraID"
          type: "string"
          in: "query"
          description: "The ID of the actual digital back object"
          required: true
      responses: 
        200: 
          description: "Returns 0 if the capture was successful"
          schema: 
            type: "integer"



